package org.tron.core.config.args;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;

/**
 * Shape of a PQ witness key JSON file referenced from {@code localPqWitness.keys}.
 * Each file holds one keypair. Exactly one material source is supplied:
 * {@code seed}, or {@code privateKey} (plus {@code publicKey} for schemes whose
 * public key BouncyCastle cannot derive from the private key, i.e. FN_DSA_512).
 * For ML_DSA_44 the public key is derived from the private key, so
 * {@code publicKey} must be omitted. Parsed by Jackson in {@link WitnessInitializer}.
 *
 * <p>An optional {@code address} (base58check) may be declared; when present it is
 * cross-checked against the address derived from the resolved public key. Files
 * generated by {@code Toolkit.jar pqkey new} include all of the fields below:
 *
 * <pre>
 *   {
 *     "scheme": "FN_DSA_512",
 *     "seed": "&lt;hex&gt;",
 *     "privateKey": "&lt;hex&gt;",
 *     "publicKey": "&lt;hex&gt;",
 *     "address": "&lt;base58check&gt;"
 *   }
 * </pre>
 *
 * <p>Minimal hand-written forms are also accepted, e.g.
 * {@code { "scheme": "ML_DSA_44", "privateKey": "&lt;hex&gt;" }}.
 */
@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
public class PqKeyFile {

  private String scheme;
  private String seed;
  private String privateKey;
  private String publicKey;
  private String address;
}
